[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bintang"
version = "0.2.47"
description = "A tiny and temporary db for quick data cleansing and transformation. It is a high-level Python coding and would help any Pythonistas up to speed with ETL work."
readme = "README.rst"

[project.optional-dependencies]
validation = [
    "python-dateutil",  # for to_datetime() and to_timedelta()
	"rapidfuzz" # to take over difflib.SequenceMatcher
	]
database = [
    "pyodbc",    # for to_sql() and read_sql using ODBC connection
	"psycopg",   # for to_sql() and read_sql() for Postgresql specifically
	"pymssql"    # for to_sql() and read_sql() for SQL Server specifically
]
excel = [
    "openpyxl",   # for read_excel() and to_excel() using .xlsx file
	"xlrd",       # for read_excel() when to read .xls file
	"xlwt"       # for to_excel() using .xls file
]
all = [
	"python-dateutil",
	"rapidfuzz",
	"pyodbc",
	"psycopg",
	"pymssql", 
	"openpyxl",   
	"xlrd",       
	"xlwt"
]
dev = [
	"build",
	"pytest",
	"twine"
]

[tool.setuptools.packages.find]
where = ["src"]  # This tells setuptools to look inside the src folder

[tool.pytest.ini_options]
testpaths = ['tests']