name: Publish bintang to PyPI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ] 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # for setup tool sees the tags
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install and Test
        run: |
          pip install pytest
          pip install -e .
          pytest
      - name: Run tests with coverage
        run: |
          pytest --cov=src --cov-report=xml tests/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}   
  publish:
    needs: test # Only runs if tests pass
    if: startsWith(github.ref, 'refs/tags') # Only runs on version tags
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build and Upload
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          pip install build twine
          python -m build
          twine upload dist/*